[package]
name = "game"
version = "0.1.0"
authors = ["William Hua <william@attente.ca>"]
edition = "2018"

[lib]
crate-type = ["lib"]

[dependencies]
wasm-bindgen = { version = "0.2.34", optional = true }

[features]
default = ["std"]
std = []
bindings = ["std", "wasm-bindgen"]
