[package]
name = "std-tester"
version = "0.1.0"
authors = ["William Hua <william@attente.ca>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arcadeum = { path = "..", default-features = false }
