[package]
name = "arcadeum"
version = "0.11.0"
authors = ["Horizon Blockchain Games"]
edition = "2018"

[features]
default = ["std"]
tester = []
debug = ["bindings", "web-sys"]
bindings = ["std", "wasm-bindgen", "js-sys", "rand_core"]
std = ["rand/std", "serde/std", "serde_cbor/std", "replace_with/std"]

[dependencies]
libsecp256k1 = "0.3.3"
tiny-keccak = "1.4.2"
rand = { version = "0.7.0", default-features = false }
rand_xorshift = "0.2.0"
serde = { version = "1.0.101", default-features = false, features = ["derive"] }
replace_with = { version = "0.1.3", default-features = false, features = ["nightly"] }
wasm-bindgen = { version = "0.2.48", optional = true, features = ["serde-serialize"] }
js-sys = { version = "0.3.25", optional = true }
rand_core = { version = "0.5.0", optional = true }
web-sys = { version = "0.3.25", optional = true, features = ["console"] }
erased-serde = "0.3.9"
objekt = "0.1.2"
serde_cbor = { version = "0.10.2", default-features = false, features = ["alloc"] }
