[package]
name = "arcadeum"
version = "0.1.0"
authors = ["Horizon Blockchain Games"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libsecp256k1 = "0.2.2"
tiny-keccak = "1.4.2"

[dev-dependencies]
libsecp256k1-rand = { package = "rand", version = "0.4.6" }
