[package]
name = "arcadeum-state"
version = "0.1.0"
authors = ["William Hua <william@attente.ca>"]
edition = "2018"

[lib]
crate-type = ["lib"]

[features]
default = ["std"]
std = []
bindings = ["std", "wasm-bindgen"]

[dependencies]
wasm-bindgen = { version = "0.2.38", optional = true }
