[package]
name = "arcadeum-state"
version = "0.1.0"
authors = ["William Hua <william@attente.ca>"]
edition = "2018"

[lib]
crate-type = ["lib"]

[features]
default = ["std"]
std = ["rand"]
bindings = ["std", "wasm-bindgen", "serde/derive"]

[dependencies]
wasm-bindgen = { version = "0.2.38", optional = true }
serde = { version = "1.0.89", optional = true }
tiny-keccak = "1.4.2"
rand = { version = "0.6.5", optional = true }
rand_core = "0.4.0"
